aws:
  access_key_id: '123'
  receive_message:
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
  region: eu-west-1
  secret_access_key: 'xyz'
  concurrency: 25
  delay: 0
  queues:
    - [ default, 6 ]
